spring:
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate.SQL: error

stripe:
  enabled: ${STRIPE_ENABLED}
  secret-key:  #${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  success-url: ${STRIPE_SUCCESS_URL}
  cancel-url: ${STRIPE_CANCEL_URL}
