spring:
  datasource:
    url: jdbc:postgresql://${UFLEX_DB_HOST:localhost}:${UFLEX_DB_PORT:5432}/${UFLEX_DB_NAME:uflex_db}?sslmode=require
    username: ${UFLEX_DB_USERNAME:admin}
    password: ${UFLEX_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate.SQL: info
