server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${UFLEX_DB_HOST:localhost}:${UFLEX_DB_PORT:5432}/${UFLEX_DB_NAME:uflex_db_dev}?sslmode=${UFLEX_DB_SSLMODE:disable}
    username: ${UFLEX_DB_USERNAME:admin}
    password: ${UFLEX_DB_PASSWORD:password}

logging:
  level:
    org.hibernate.SQL: info
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: error